blog/urls.py
from .views import views
from .views import ajax_views
from django.urls import path ,include

app_name = "blog"

urlpatterns =[
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('blog/posts/',views.blog_index,name='blog_index'),
    path('posts/<slug:slug>/detail/',views.blog_detail,name='detail'),
    path('projects/',views.ProjectListView.as_view(),name='projects'),
    path('projects/<slug:slug>/detail/',views.ProjectDetail.as_view(),name='project-detail'),

        path('ajaxIndex/',ajax_views.ajaxIndex,name="ajaxIndex"),
        path('resume/pdf/',views.resumepdf,name='resumepdf'),
    
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog.urls")),
   # path('polls/',include("polls.urls")),
   ]

urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
import markdown

STATUS_CHOICES = (
        ('unread','unread'),
        ('in_progress','in_progress'),
        ('completed','completed'),
        )


class Post(models.Model):
    
    author = models.ForeignKey(User,on_delete = models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    slug = models.SlugField(max_length=250,unique=True, null=True, blank=True)
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def save(self,*args,**kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            counter = 0

            while Post.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def preview(self):
        return self.text[:100]

    def published(self):
        if self.published_date<timezone.now():
            return True
        else:
            return False
    
    def parse_md(self):
        return markdown.markdown(self.text,extensions=['fenced_code', 'codehilite', 'toc', 'tables'])


    class Meta:
        ordering = ("-published_date",)

class About(models.Model):
    text = models.TextField()

    def __str__(self):
        return f"About -- {self.id}"

    def parse_md(self):
        return markdown.markdown(self.text,extensions=['fenced_code', 'codehilite', 'toc', 'tables'])



class Contact(models.Model):
    info = models.TextField() 
    
    def parse_md(self):
        return markdown.markdown(self.info,extensions=['fenced_code', 'codehilite', 'toc', 'tables'])


class Project(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=300,unique=True,blank=True,null=True)
    description = models.TextField()
    image = models.ImageField(upload_to='projects',blank=True)
    technologies_used = models.CharField(max_length=500)
    github = models.CharField(max_length=500,blank=True)
    demo = models.CharField(max_length=500,blank=True)
    featured = models.BooleanField(default=False)

    def save(self,*args,**kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            slug = base_slug
            counter = 0

            while Post.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:project-detail',kwargs = {'slug':self.slug})

    def get_technologies_used_list(self):
        return self.technologies_used.split(',')



class ClientMessage(models.Model):
    email = models.EmailField()
    message = models.TextField()
    status = models.CharField(choices=STATUS_CHOICES,default="unread",max_length=12)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.status} {self.timestamp.strftime("%d %h %Y--%H:%M:%S")}'

    class Meta:
        ordering = ("-timestamp",)


class Resume(models.Model):
    file = models.FileField(upload_to='documents')




    

blog/forms.py
from django import forms

class NameForm(forms.Form):
    website_url = forms.CharField(max_length=100)
    result = forms.CharField(widget=forms.Textarea)

class MessageForm(forms.Form):
    email = forms.EmailField(widget = forms.EmailInput(attrs = {
        "class" : "form-control text-input",
        "placeholder" : "Email",
        }
                                                       ) )
    message = forms.CharField(widget = forms.Textarea(attrs = {
        "class" : "form-control",
        "placeholder" : "Type a message"
        }
        ))

blog/views/ajax_views.py
#this module contains code for views involving AJAX
from django.http import JsonResponse
from ..models import Post
from django.urls import reverse
#none view code below
def helper(lst):
    dct = {}
    for i in lst:
        dct[i.id] = {"id":i.id,"title":i.title,"pub_date":i.published_date,"preview":i.preview(),"url":reverse("blog:detail",args=(i.id,))}
    return dct

def ajaxIndex(request):
    post = Post.objects.all()[:3] 
    data = helper(post)
    return JsonResponse(data)
        

blog/views/views.py
from django.shortcuts import render,get_object_or_404,get_list_or_404,redirect
from ..models import Post,About,Contact,Project,ClientMessage,Resume
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView , ListView
from  ..forms import MessageForm
from django.urls import reverse,reverse_lazy
from django.http import JsonResponse,FileResponse
import json
from django.contrib.auth.models import User
from django.db import IntegrityError
from ..utils import auto_mail_reply
from django.views.decorators.cache import never_cache



def index(request):
    about = About.objects.all()
    about = None if len(about)==0 else about[0]
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by("-published_date")[:3]

    context = {
            "about" : about,
            "posts" : posts,
            }

    return render(request,"blog/index.html",context)


def about(request):
    about = About.objects.all()
    about = None if len(about)==0 else about[0]
    context = {"about":about}
    return render(request,"blog/about.html",context)

@never_cache
def contact(request):

    if request.method == "POST":

        email = request.POST.get('email')
        message = request.POST.get('message')
        ClientMessage.objects.create(email = email, message = message)
        auto_mail_reply(email)

        return JsonResponse({'msg':'success'})
    contact = Contact.objects.all()
    contact = None if len(contact)==0 else contact[0]
    msgform = MessageForm()
    context ={
            "contact":contact,
            "message_form":msgform,
            }
    return render(request,"blog/contact.html",context)

def blog_index(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by("-published_date")[:3]

    context = {
            "posts" : posts,
            }
    return render(request,"blog/blog_index.html",context)

def blog_detail(request,slug):
    post = get_object_or_404(Post,slug=slug,published_date__lte=timezone.now())
    context = {
            "post":post,
            }
    return render(request,"blog/detail.html",context)

class ProjectListView(ListView):
    model = Project
    template_name = 'blog/projects.html'
    context_object_name = 'projects'

class ProjectDetail(DetailView):
    model = Project
    template_name = 'blog/project_detail.html'
    context_object_name = 'project'

def resumepdf(request):
    file = get_object_or_404(Resume,pk=1).file

    return FileResponse(file,filename='michael_ayeni_resume.pdf')


    

blog/templates/blog/about.html
{% extends "blog/generic_base.html" %}
{% block head %}
<title>About</title>
{% endblock %}

{% block content %}
<h2 class="font-bold text-4xl text-center mb-10"> About</h2>
{% if about %}
<article class="prose dark:prose-invert text-[18px] mb-[60px] anim">
{{about.parse_md|safe}}
  </article>
<a class="block p-3 m-auto rounded-[25px] text-[#fff] bg-green-500 font-bold text-[16px] text-center anim" href="{% url 'blog:contact' %}">Get In Touch</a>
{% else %}
<div class="alert alert-warning" > No about</div>
{% endif %}
{% endblock %}

blog/templates/blog/blog_index.html
{% extends "blog/generic_base.html" %}
{% block head %}
<title>Blog</title>{% endblock head %}

{% block content %}

<p class="mb-[60px]" >You want to read some interesting write up about what I think and who I am, my journey, struggles and success? then check out these blog posts below. </p>
  <h2 class="text-3xl text-center font-[450] mb-2" >Articles</h2>
  <hr class="border-[rgba(0,255,0,0.4)] border-2 mb-2">
                 <p class="font-mono font-extrabold text-6xl text-green-500 text-center m-2 mb-5">...</p>

{% if posts %}
{% for post in posts %}
<a href="{% url 'blog:detail' post.slug %}" >
	<article class="card">
		<h3 class="text-[#333] dark:text-[#ccc] font-bold mb-3 text-[22px]">{{post.title}}</h3>
		<div class="prose dark:prose-invert" >{{post.parse_md|safe|truncatewords:20}}</div>
		 <a href="{% url 'blog:detail' post.slug %}" class="block text-center w-1/2 rounded-[25px] text-[#eee] bg-blue-500 m-3 p-3 ml-[45%] font-bold">Read more</a>
	</article>
</a>

{% endfor %}
{% else %}
  		
<article> No posts available </article>
{% endif %} 

{% endblock content %}

blog/templates/blog/contact.html
{% extends "blog/generic_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block head %}
<title>Contact</title>
<script type="text/javascript">
	const MESSAGE_URL = {% url 'blog:contact' %}
</script>
<script type='text/javascript' src="{% static 'blog/js/message.js' %}"></script>
{% endblock %}

{% block content %}
<h2 class="text-center text-3xl font-bold mt-5 mb-[30px]" >Contact Me</h2>
{% if contact %}
<section class="p-2 mb-[60px] prose dark:prose-invert">
  {{contact.parse_md|safe}}
</section>
{% else %}
<div class="alert alert-warning mt-8 mb-[60px]">
No Contact info available
</div>
{% endif %}
 
<form class="form" id='message-form' method='POST'>
	<b>Send A Message</b>
	<div id="alert-box">
	</div>
	{% csrf_token %}
	<div class="fieldset">
	<label for="{{message_form.email.id_for_label}}"><span class="fg-red">*</span></label><br>
	{{message_form.email}}
	{{message_form.email.errors}}
	</div>
	
		<div class="fieldset">
	<label for="{{message_form.message.id_for_label}}"><span class="fg-red">*</span></label><br>
	{{message_form.message}}
	{{message_form.message.errors}}
	</div>
	<div class="fieldset">
	<button type="submit" class="block w-4/5 m-auto mt-10 text-[#fff] font-bold bg-green-500 rounded-[25px] p-3">Submit</button>
		<div>
</form>

{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/generic_base.html" %}

{% block head %}
<title>post detail</title>
{% endblock %}

{% block content %}
<a href="/" style="font-size:20px; width:5em;" class="text-blue-500 hover:underline block mb-[50px]">  << back </a>
<article class="card">
  <h1 class="text-3xl mb-5" >{{post.title}}</h1>
  <time class="mb-5 block">published: {{post.published_date}}
  </time>
  <div class="prose dark:prose-invert">
  {{post.parse_md|safe}}
  </div>
</article>

<br/>
{% endblock %}

blog/templates/blog/generic_base.html
<!DOCTYPE html> 

<html> 
	<head>
  <meta http-equiv="CONTENT-TYPE"content="text/html; charset=UTF-8">

  <meta name="viewport"content="width=device-width,initial-scale=1.0">

<meta name="description" content="Michael Ayeni is a pragmatic software developer with experience in Django, Python, React, and backend-focused problem solving. Passionate about building real-world applications like Vendora and crafting efficient, well-structured systems.">

<meta name="keywords" content="Michael Ayeni, software developer, Django developer, Python developer, React developer, backend developer, portfolio, web developer in Nigeria, Vendora">

<meta name="robots" content="index, follow">

<link rel="canonical" href="https://granzular.pythonanywhere.com">

<!-- Open Graph -->
<meta property="og:title" content="Michael Ayeni – Software Developer Portfolio">
<meta property="og:description" content="Portfolio of Michael Ayeni, a Fullstack Software developer building practical, real-world applications with clean architecture and strong backend skills.">
<meta property="og:image" content="https://granzular.pythonanywhere.com/static/images/portfolio-preview.jpg">
<meta property="og:url" content="https://granzular.pythonanywhere.com">
<meta property="og:type" content="website">

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Michael Ayeni – Software Developer Portfolio">
<meta name="twitter:description" content="Software developer skilled in Django, Python, React, and backend engineering. View my projects and developer journey.">
<meta name="twitter:image" content="https://granzular.pythonanywhere.com/static/images/portfolio-preview.jpg">

<!-- Structured Data -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Michael Ayeni",
  "url": "https://granzulla.pythonanywhere.com",
  "jobTitle": "Software Developer",
  "description": "Software developer skilled in Django, Python, React, and backend-focused engineering. Builder of Vendora and other practical web applications.",
  "image": "https://granzulla.pythonanywhere.com/static/images/portfolio-preview.jpg"
}
{% load static %}
</script>
    <!-- tailwindcss and font awesome -->
    <link rel="stylesheet" href="{% static 'blog/src/output.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" />
{% load static %}
<link rel="stylesheet" href="{% static 'blog/css/style.css'%}"/>
<link rel="stylesheet" href="{% static 'blog/css/navbar.css' %}" />


<link rel="icon" type="image/png" href="/media/images/favicon.jpg"/>

<script>
	STATIC_URL = "{% static 'blog/'  %}"
	AJAX_URL = "{% url 'blog:ajaxIndex' %}"
</script>

<script type="text/javascript" src="{% static 'blog/js/navbar.js' %}"></script>
  <script  type="text/javascript" src="{% static 'blog/js/theme.js' %}"></script>
    <script  type="text/javascript" src="{% static 'blog/js/main.js' %}"></script>

  
{% block head %} {% endblock %}
</head> 

<body class="dark:text-[#eee] dark:bg-[#222]" >
  <header>
	  {% include 'blog/navbar.html'   %}
  </header>
 <section   class="feature-box">
	 <div>
	 </div>
<div></div>
    <div></div>
  </section>
 <main class="content">
{% block content %}
{% endblock %}
  
 </main>
 <br/>
 <br/>
 <br/>
 
  <footer>
    <hr>
    <div style="display:flex;justify-content:center;">
      <a href="https://github.com/Granzular"> <img src="/media/images/github.svg" alt="github icon"></a>
      <a href=""><img src="/media/images/linkedin.svg" alt="linkedin icon"> </a>
      
    </div>

    <p class="p-2">granzularcodex</p> 
   <p class="p-2"> copyright©2024-<span class="" id="year"></span> </p>
</footer>
{% block end %}
{% endblock %}

</body> 
<script type="application/javascript">
const year = new Date().getFullYear();
document.querySelector("#year").textContent = year;
</script>
</html>


    
    

blog/templates/blog/index.html
{% extends "blog/generic_base.html" %}
{% block head %}
  <title>Home</title>
  <script>
  let BASE_URL = "{% url 'blog:index' %}";
  let DETAIL_URL = "{% url 'blog:detail' 4 %}";
  </script>
{% endblock %}
  {% block content %}
<div class="index-hero m-auto mb-[200px] p-5 anim">
		<div class="mb-[80px]">
		
		<h2 class="text-2xl mt-10 mb-[60px]"><span
				 class="text-5xl">Hi</span><br>I'm<strong class="text-bold text-green-500 text-3xl"> Michael Ayeni</strong><br>software developer</h2>

		<p class="text-[#222] dark:text-[#eee]">
		with a passion for creating quality software.<br><em class="text-gray-500">Turning idea into code, and code into reality</em></p>
		
		<a href="{% url 'blog:resumepdf' %}" class="bg-blue-500 text-white rounded-[25px] font-bold block m-auto mt-[40px] mb-[50px] p-4 text-center">Download Resume</a>

		</div>
		<div class="card-img mb-10 anim">
				<img src="/media/images/profile_pic.jpg" id="profile-img" alt="my profile picture">
		</div>
		<div class="mt-5 anim">
		<a href="{% url 'blog:contact' %}" class="rounded-[25px] bg-green-500 text-white font-bold p-4" >Contact Me</a>
  <a class="rounded-[25px] border-[1px] border-[#222] bg-[rgba(255,255,255,0.3)] font-bold p-4" href="{% url 'blog:projects' %}">My Works</a><br>
</div>
</div>
	
<div class="index-about m-auto mb-[200px] p-4 pt-10 bg-gray-800 anim" id="about">
<h2 class="heading text-center text-4xl font-bold mb-8 text-blue-300"> About</h2>
		 
{% if about %}
<article class="m-auto font-[450] text-[18px] prose  text-center text-white">
{{about.parse_md|safe|truncatewords:50}}

<a class="text-center text-white block rounded-[25px] p-3 m-5 bg-blue-500 font-bold" href="{% url 'blog:about' %}">Learn More</a>
  </article>
{% else %}
<div class="alert alert-warning anim">No about</div>
{% endif %}
</div>


<div class="anim">
		 <h2 class=" text-center text-3xl font-[450] p-4">Articles</h2>
		 <hr class="border-[rgba(0,255,0,0.4)] border-2 mb-2">
		 <p class="font-mono font-extrabold text-6xl text-green-500 text-center m-2 mb-4">...</p>
		 
		 
		 {% if posts %}
		 {% for post in posts %}
	<article class="border-1 text-[rgba(255,255,255,0.4)] p-1 mb-10 anim">
		<h3 class="text-[#333] dark:text-[#ccc] font-bold mb-2 text-[22px]">{{post.title}}</h3>
		
		<div class="prose dark:prose-invert anim">{{post.parse_md|safe|truncatewords:20}}</div>
			 <a href="{% url 'blog:detail' post.slug %}" class="block text-center w-1/2 rounded-[25px] text-[#eee] bg-blue-500 m-3 p-3 ml-[45%] font-bold">Read more</a>
	</article>

{% endfor %}
		 {% else %}
		 <div class="alert alert-warning anim" >No posts available </div>
		 {% endif %}
</div>
	{% endblock %}

blog/templates/blog/navbar.html
{% load static %}

        <nav class="top-nav">
          
          <a id="logo-a" href="/"><img src="/media/images/favicon.jpg" class="inline-block" id="brand-logo"  alt='brand logo'></a>
        
          
        <div class="navbar-ul bg-[rgba(255,255,255,1)] dark:bg-[#333]" id="navbar-ul" >
          
          <img src="{% static 'blog/images/close.png' %}" class="dark:invert nav-icon" id="close-icon">
          <ul>
  <li ><a class="nav-link dark:text-[#eee]"  href="/">Home</a></li>
          <li><a class="nav-link dark:text-[#eee] " href="{% url 'blog:about' %}"> About</a></li>
          <li ><a class="nav-link dark:text-[#eee] " href="{% url 'blog:projects' %}">My Works</a></li>
          <li><a class="nav-link dark:text-[#eee] " href="{% url 'blog:contact' %}">Contact</a></li>
          <li ><a class="nav-link dark:text-[#eee] " href="{% url 'blog:blog_index' %}">Blog</a></li>
        </ul>   
        </div>
          
          <img class="dark:invert" id="theme-toggle-icon" src="/media/images/moon.svg" alt="🌙">
          <img   src="{% static 'blog/images/menuicon01.png' %} " id="menu-icon" class="dark:invert nav-icon" alt="menu">
          
  </nav>
   <!-- <a href="/" class="website-name-link"> <h1 class="website-name">GRANZULAR CODEX</h1></a>-->

blog/templates/blog/portfolioDetail.html
{% extends "blog/generic_base.html" %}
                                                      {% block head %}                                      <title>Portfolio</title>
{% endblock head %}                                   
{% block content %}
{% if project %}
<div class="card " > 
	<img src="{{project.image.url}}" class="card-img-top pl-2 w-100 h-100" >
	<div class="card-body">                                       <h5 class="card-title">{{project.title}}</h5>                                                     <strong>Description</strong>                                  <p class="card-text">{{project.description}}</p>
		<strong>Languages and Framework</strong>
          <ul class="list-group">
		  {% for line in project.get_technologies_used_list %}
		  <li class="list-group-item" >{{line}} </li>
		  {% endfor %}
	  </ul>
	  <strong>Links</strong>

	  <ul class="list-group">                                       {% for line in project.get_links_list %}                                                                     <li class="list-group-item" >{{line|urlize}}</li>                                                         </ul>
	  

  </div>
</div>

{% endfor %}
{% else %}
<div class="alert alert-warning" role="alert">
No projects Available.
</div>
{% endif %}
{% endblock content %}

blog/templates/blog/project_detail.html
{% extends "blog/generic_base.html" %}
{% load custom_filters %}
{% block head %}

<title>Portfolio</title>

{% endblock head %}                                   
{% block content %}
{% if project %}
<div class="mb-10 p-3" >
	 <h3 class="text-2xl font-[450]  mb-5">Project Title: {{project.title}}</h3> 
	<img src="{{project.image.url}}" class="card-img-top pl-2 w-100 h-100" >
	<div class="">
		<h4 class="text-[20px] font-[450] mt-5 mb-2" >Description</h4>
		<p class="dark:text-[#eee] text-[16px] mb-5">{{project.description}}</p>
		<h4 class="text-[20px] font-[450] mt-5 mb-2" >Languages and Framework</h4>
          <ul class="mb-5 dark:text-[#eee]">
		  {% for line in project.get_technologies_used_list %}
		  <div class="block m-3 mb-10">
			  <li class="font-bold text-[16px] inline-block" >{{line}} </li>
			  <div class="inline-block">{{line|logo|safe}}</div>

		  </div>
		  {% endfor %}
	  </ul>
	  <h3 class="text-2xl font-[450] mb-5">Links</h3>
	  <p><b>Github: </b><a class="text-[skyblue]" href="{{project.github}}">{{project.github}}</a></p>
	  <b>Demo: </b><a class="text-[skyblue]" href="{{project.demo}}">{{project.demo}}</a>

  </div>
</div>

{% else %}
<div class="alert alert-warning" role="alert">
No projects Available.
</div>
{% endif %}
{% endblock content %}

blog/templates/blog/projects.html
{% extends "blog/generic_base.html" %}

{% block head %}
<title>My Works</title>
{% endblock head %}

{% block content %}
<h2 class="text-center text-3xl font-bold mb-10 "> Projects </h2>
{% if projects %}
{% for project in projects %}
<div style="background: url('{{project.image.url}}');" class="rounded-[15px] mb-[20px] bg-cover bg-no-repeat border-[2px] border-green-500 mb-10" >
                                                    <div class="rounded-[14px]  p-2 backdrop-blur-[10px] w-[100%] h-[100%] bg-[rgba(255,255,255,0.2)] ">                                       <h4 class="font-bold text-2xl mb-[5px] text-[#222]">{{project.title}}</h4>
		<p class="mb-[5px] text-[18px] font-[400] text-[#333]">{{project.description|truncatewords:20}}</p>
                                                    		<div class=" m-auto mt-5">                                            	
    <a href="{{project.get_absolute_url}}" class="rounded-[25px] inline-block w-1/3 bg-green-500 text-[#fff] font-bold p-3 text-center">Details</a>
    <a href="{{project.demo}}" class="rounded-[25px] inline-block w-1/3 text-green-500 bg-[none] border-[1px] border-green-500 text-[#fff] font-bold p-3 text-center text-[rgba(255,255,255,0.5)] backdrop-blur-[16px] ">Demo</a>                                                   				                                                    		</div>                                    
  </div>
</div>

{% endfor %}
{% else %}
<div class="alert alert-warning" role="alert">
No projects Available.
</div>
{% endif %}
<br>



{% endblock content %}